[package]
name = "velopack_flutter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.7.0"
velopack = { version = "0.0", features= ["async"]}
anyhow = "1.0.86"
